services:
  service-registry:
    build: service-registry
    ports:
      - "8761:8761"
    networks:
      - has-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
  api-gateway:
    build: api-gateway
    ports:
      - "8080:8080"
    networks:
      - has-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
    depends_on:
      service-registry:
        condition: service_healthy
  user-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=user-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - user-data:/var/lib/postgresql/data:rw
    networks:
      - has-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  doctor-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=doctor-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - doctor-data:/var/lib/postgresql/data:rw
    networks:
      - has-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  user-service:
    build: user-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - has-network
    depends_on:
      user-db:
        condition: service_healthy
      service-registry:
        condition: service_healthy
volumes:
  user-data:
  doctor-data:
networks:
  has-network:
